//
//  CountryDict.swift
//  CovidSimpleApp
//
//  Created by Furkan on 16.05.2020.
//  Copyright © 2020 Furkan İbili. All rights reserved.
//

import Foundation

/**
 This class is a country dictionary. API return country name with English but we need Turkish names.
 Use with singleton structure.
 */
class CountryDict {
    
    //Singleton
    static let shared = CountryDict()
    
    //EN-TR Country Dictionary
    let countries:[String:String] = [
    "USA":"Amerika Birleşik Devletleri",
    "Spain":"ispanya",
    "Italy":"İtalya",
    "France":"Fransa",
    "Germany":"Almanya",
    "UK":"UK",
    "Turkey":"Türkiye",
    "Iran":"İran",
    "China":"Çin",
    "Russia":"Rusya",
    "Brazil":"Brezilya",
    "Belgium":"Belçika",
    "Canada":"Kanada",
    "Netherlands":"Hollanda",
    "Switzerland":"İsviçre",
    "Portugal":"Portekiz",
    "India":"Hindistan",
    "Peru":"Peru",
    "Sweden":"İsveç",
    "Ireland":"İrlanda",
    "Austria":"Avusturya",
    "Israel":"İsrail",
    "Saudi Arabia":"Suudi Arabistan",
    "Japan":"Japonya",
    "Chile":"Şili",
    "Singapore":"Singapur",
    "Ecuador":"Ekvador",
    "Pakistan":"Pakistan",
    "S. Korea":"Güney Kore",
    "Mexico":"Meksika",
    "Poland":"Polonya",
    "Romania":"Romanya",
    "UAE":"BAE",
    "Denmark":"Danimarka",
    "Indonesia":"Endonezya",
    "Qatar":"Katar",
    "Norway":"Norveç",
    "Belarus":"Belarus",
    "Ukraine":"Ukrayna",
    "Czechia":"Çekya",
    "Serbia":"Sırbistan",
    "Philippines":"Filipinler",
    "Australia":"Avustralya",
    "Malaysia":"Malezya",
    "Dominican Republic":"Dominik Cumhuriyeti",
    "Panama":"Panama",
    "Colombia":"Kolombiya",
    "Finland":"Finlandiya",
    "Bangladesh":"Bangladeş",
    "Egypt":"Mısır",
    "Luxembourg":"Lüksemburg",
    "South Africa":"Güney Afrika",
    "Morocco":"Fas",
    "Argentina":"Arjantin",
    "Algeria":"Cezayir",
    "Thailand":"Tayland",
    "Moldova":"Moldova",
    "Greece":"Yunanistan",
    "Kuwait":"Kuveyt",
    "Hungary":"Macaristan",
    "Kazakhstan":"Kazakistan",
    "Bahrain":"Bahreyn",
    "Croatia":"Hırvatistan",
    "Iceland":"İzlanda",
    "Oman":"Umman",
    "Uzbekistan":"Özbekistan",
    "Iraq":"Irak",
    "Estonia":"Estonya",
    "Azerbaijan":"Azerbeycan",
    "Armenia":"Ermenistan",
    "New Zealand":"Yeni Zelanda",
    "Bosnia":"Bosna",
    "Lithuania":"Litvanya",
    "Slovenia":"Slovenya",
    "Slovakia":"Slovakya",
    "Macedonia":"Makedonya",
    "Afghanistan":"Afganistan",
    "Cuba":"Küba",
    "Cameroon":"Kamerun",
    "Ghana":"Gana",
    "Bulgaria":"Bulgaristan",
    "Hong Kong":"Hong Kong",
    "Djibouti":"Cibuti",
    "Côte d'Ivoire":"Fildişi Sahili",
    "Tunisia":"Tunus",
    "Nigeria":"Nijerya",
    "Cyprus":"Kıbrıs",
    "Latvia":"Letonya",
    "Guinea":"Gine",
    "Andorra":"Andorra",
    "Diamond Princess":"Elmas Prenses",
    "Lebanon":"Lübnan",
    "Costa Rica":"Kosta Rika",
    "Bolivia":"Bolivya",
    "Albania":"Arnavutluk",
    "Niger":"Nijer",
    "Kyrgyzstan":"Kırgızistan",
    "Burkina Faso":"Burkina Faso",
    "Uruguay":"Uruguay",
    "Honduras":"Honduras",
    "Channel Islands":"Kanal Adaları",
    "San Marino":"San Marino",
    "Palestine":"Filistin",
    "Senegal":"Senegal",
    "Malta":"Malta",
    "Jordan":"Ürdün",
    "Taiwan":"Tayvan",
    "Georgia":"Gürcistan",
    "Réunion":"Réunion",
    "DRC":"DRC",
    "Guatemala":"Guatemala",
    "Sri Lanka":"Sri Lanka",
    "Mauritius":"Mauritius",
    "Mayotte":"Mayotte",
    "Montenegro":"Karadağ",
    "Isle of Man":"Man Adası",
    "Kenya":"Kenya",
    "Venezuela":"Venezuela",
    "Mali":"Mali",
    "Somalia":"Somali",
    "Tanzania":"Tanzanya",
    "Vietnam":"Vietnam",
    "Jamaica":"Jamaika",
    "El Salvador":"El Salvador",
    "Paraguay":"Paraguay",
    "Faroe Islands":"Faroe Adaları",
    "Congo":"Kongo",
    "Gabon":"Gabon",
    "Martinique":"Martinik",
    "Sudan":"Sudan",
    "Rwanda":"Ruanda",
    "Guadeloupe":"Guadeloupe",
    "Brunei":"Brunei",
    "Gibraltar":"Cebelitarık",
    "Myanmar":"Myanmar",
    "Cambodia":"Kamboçya",
    "Madagascar":"Madagaskar",
    "Ethiopia":"Etiyopya",
    "Trinidad and Tobago":"Trinidad ve Tobago",
    "French Guiana":"Fransız Guyanası",
    "Liberia":"Liberya",
    "Aruba":"Aruba",
    "Bermuda":"Bermuda",
    "Maldives":"Maldivler",
    "Monaco":"Monako",
    "Togo":"Gitmek",
    "Equatorial Guinea":"Ekvator Ginesi",
    "Cabo Verde":"Cabo Verde",
    "Liechtenstein":"Lihtenştayn",
    "Barbados":"Barbados",
    "Zambia":"Zambiya",
    "Sint Maarten":"Sint Maarten",
    "Bahamas":"Bahamalar",
    "Guyana":"Guyana",
    "Cayman Islands":"Cayman Adaları",
    "Uganda":"Uganda",
    "Haiti":"Haiti",
    "Sierra Leone":"Sierra Leone",
    "Libyan Arab Jamahiriya":"Libya Arap Jamahiriya",
    "French Polynesia":"Fransız Polinezyası",
    "Benin":"Benin",
    "Guinea-Bissau":"Gine-Bissau",
    "Nepal":"Nepal",
    "Macao":"Macao",
    "Syrian Arab Republic":"Suriye Arap Cumhuriyeti",
    "Mozambique":"Mozambik",
    "Eritrea":"Eritre",
    "Saint Martin":"Aziz Martin",
    "Mongolia":"Moğolistan",
    "Chad":"Çad",
    "Malawi":"Malawi",
    "Swaziland":"Svaziland",
    "Zimbabwe":"Zimbabve",
    "Angola":"Angora",
    "Antigua and Barbuda":"Antigua ve Barbuda",
    "Timor-Leste":"Timor-Leste",
    "Botswana":"Botsvana",
    "Lao People's Democratic Republic":"Lao Demokratik Halk Cumhuriyeti",
    "Belize":"Belize",
    "Fiji":"Fiji",
    "New Caledonia":"Yeni Kaledonya",
    "Dominica":"Dominika",
    "Namibia":"Namibya",
    "Grenada":"Grenada",
    "Saint Kitts and Nevis":"Saint Kitts ve Nevis",
    "Saint Lucia":"Saint Lucia",
    "Central African Republic":"Orta Afrika Cumhuriyeti",
    "Curaçao":"Curacao",
    "Saint Vincent and the Grenadines":"Saint Vincent ve Grenadinler",
    "Falkland Islands (Malvinas)":"Falkland Adaları (Malvinas)",
    "Burundi":"Burundi",
    "Greenland":"Grönland",
    "Montserrat":"Montserrat",
    "Seychelles":"Seyşeller",
    "Turks and Caicos Islands":"Turks ve Caicos Adaları",
    "Gambia":"Gambiya",
    "Nicaragua":"Nikaragua",
    "Suriname":"Surinam",
    "Holy See (Vatican City State)":"Holy See (Vatikan Şehir Devleti)",
    "MS Zaandam":"MS Zaandam",
    "Papua New Guinea":"Papua Yeni Gine",
    "Bhutan":"Butan",
    "Mauritania":"Moritanya",
    "St. Barth":"St. Barth",
    "Western Sahara":"Batı Sahra",
    "British Virgin Islands":"İngiliz Virgin Adaları",
    "Caribbean Netherlands":"Karayip Hollandası",
    "Sao Tome and Principe":"Sao Tome ve Principe",
    "South Sudan":"Güney Sudan",
    "Anguilla":"Anguilla",
    "Saint Pierre Miquelon":"Saint Pierre Miquelon",
    "Yemen":"Yemen"]
    
}
